config/routes.rb
Rails.application.routes.draw do
  resources :jobs

  root 'home#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'sign_in', to: 'home#sign_in', as: 'sign_in'
  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

  resources :users

end

app/models/authentication.rb
class Authentication
  include Mongoid::Document
  include Mongoid::Timestamps

  field :user_id, type: String
  field :provider, type: String
  field :uid, type: String

  belongs_to :user

  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, scope: :provider

  def self.find_or_create_with_omniauth(auth)
  	find_with_omniauth(auth) || create_with_omniauth(auth)
  end

  def self.find_with_omniauth(auth)
    find_by provider: auth['provider'], uid: auth['uid']
  end

  def self.create_with_omniauth(auth)
    create(uid: auth['uid'], provider: auth['provider'])
  end

end

app/models/job.rb
class Job
  include Mongoid::Document
  include Mongoid::Timestamps
  extend Enumerize

  field :title, type: String
  field :desc, type: String
  field :company, type: String
  field :status, type: String

  enumerize :status, in: { open: 1, closed: 0 }, default: :open, predicates: true

  belongs_to :owner, class_name: "User"

  validates_presence_of :title, :owner

  def owned_by?(user)
  	user == owner
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  

  field :name, type: String
  field :desc, type: String
  field :email, type: String
  field :avatar, type: String
  field :url, type: String

  has_many :authentications
  has_many :jobs

  validates_uniqueness_of :email

  def self.from_omniauth(auth)

  	user = find_with_omniauth(auth)
  	unless user	# New User
  			user = create_from_omniauth(auth)
  	end

		unless Authentication.find_with_omniauth(auth) # New Authentication
			user.authentications << Authentication.create_with_omniauth(auth)
			user.save
		end

		return user

	end

	def self.find_with_omniauth(auth)
  	where(email: auth["info"]["email"]).first
  end

	def self.create_from_omniauth(auth)
	  user = User.new
	  user.name = auth["info"]["name"]
    user.email = auth["info"]["email"]
    user.desc = auth["info"]["description"]
    user.avatar = auth["info"]["image"]
    # user.authentications << Authentication.create_with_omniauth(auth)
    user.save!
	  return user
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  private

	  def set_locale
		  I18n.locale = extract_locale_from_tld || I18n.default_locale
		end

		# Get locale from top-level domain or return nil if such locale is not available
		def extract_locale_from_tld
		  # parsed_locale = request.host.split('.').last
		  # I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
		  parsed_locale = request.host.split('.').last == 'br' ? :pt_BR : nil
		end

	  def current_user
	    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	  end

	  def signed_in?
	    !!current_user
	  end

	  helper_method :current_user, :signed_in?

	  def current_user=(user)
	    @current_user = user
	    session[:user_id] = user.nil? ? user : user.id
	  end

	  def authorize
		  redirect_to sign_in_url, alert: t('errors.messages.not_authorized') if current_user.nil?
		end

end

app/controllers/home_controller.rb
# encoding: UTF-8
class HomeController < ApplicationController
  
  def index
  	render layout: 'public'
  end

  def sign_in
  	# render layout: 'application'
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authorize
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  def create
    @job = Job.new(job_params)
    @job.owner = current_user

    if @job.save
      redirect_to @job, notice: t('notices.create', model: t('models.job.one'))
    else
      render :new
    end
  end

  # PATCH/PUT /jobs/1
  def update
    if @job.update(job_params)
      redirect_to @job, notice: t('notices.update', model: t('models.job.one'))
    else
      render :edit
    end
  end

  # DELETE /jobs/1
  def destroy
    @job.destroy
    redirect_to jobs_url, notice: t('notices.destroy', model: t('models.job.one'))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def job_params
      params.require(:job).permit(:title, :desc, :company, :status, :owner)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create

    # raise env['omniauth.auth'].to_yaml
    user = nil
    if user = User.from_omniauth(env['omniauth.auth'])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "Signed in."
    else
      redirect_to sign_in_url, notice: "Authentication failed."
    end

  end

  # def create

  #   auth = request.env['omniauth.auth']
  #   raise env['omniauth.auth'].to_yaml
  #   # Find an authentication here
  #   @authentication = Authentication.find_with_omniauth(auth)

  #   if @authentication.nil?
  #     # If no authentication was found, create a brand new one here
  #     @authentication = Authentication.create_with_omniauth(auth)
  #   end

  #   if signed_in?
  #     if @authentication.user == current_user
  #       # User is signed in so they are trying to link an authentication with their
  #       # account. But we found the authentication and the user associated with it 
  #       # is the current user. So the authentication is already associated with 
  #       # this user. So let's display an error message.
  #       redirect_to user_path(current_user), notice: "Already linked that account!"
  #     else
  #       # The authentication is not associated with the current_user so lets 
  #       # associate the authentication
  #       @authentication.user = current_user
  #       @authentication.save()
  #       redirect_to user_path(user), notice: "Successfully linked accounts!"
  #     end
  #   else
  #     if @authentication.user.present?
  #       # The authentication we found had a user associated with it so let's 
  #       # just log them in here
  #       self.current_user = @authentication.user
  #       redirect_to user_path(current_user), notice: "Signed in!"
  #     else
  #       # No user associated with the authentication so we need to create a new one
  #       user = User.from_omniauth(env['omniauth.auth'])
  #       self.current_user = user
  #       redirect_to user_path(user), notice: "Sign Up successful!"
  #     end
  #   end

  # end

  def destroy

    self.current_user = nil
	  redirect_to sign_in_url, notice: "Signed out."
	  
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authorize

	def show
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_alert(msg, type="info")

		html = "<div class='alert alert-#{type} alert-dismissable'>"
    html +=  "<button type=button class=close data-dismiss=alert aria-hidden=true>&times;</button>"
    html +=  msg
    html += "</div>"

    return raw(html)

	end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div class="site-wrapper">

  <div class="site-wrapper-inner">

    <div class="cover-container">

      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand"><%= t 'referroll.name' %></h3>
          <ul class="nav masthead-nav">
            <li class="active"><a href="#"><%= t 'actions.home' %></a></li>
            <!-- <li><a href="#"><%= t 'actions.sign-up' %></a></li> -->
            <!-- <li><a href="#" data-toggle="modal" data-target="#signInModal"><%= t 'actions.sign-in' %></a></li> -->
            <li><%= link_to t('actions.sign-in'), sign_in_url %></li>
          </ul>
        </div>
      </div>

      <div class="inner cover">
        <h1 class="cover-heading"><%= t 'referroll.slogan' %></h1>
        <br>
        <!-- <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p> -->
        <p class="lead">
          <a href="#" class="btn btn-lg btn-warning"><%= t 'referroll.cta' %></a>
        </p>
      </div>

      <div class="mastfoot">
        <div class="inner">
          <p><%= raw t 'referroll.copyright' %>.</p>
        </div>
      </div>

    </div>

  </div>

</div>

<!-- Sign In Modal -->
<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="signInModalLabel"><%= t 'actions.sign-in' %></h4>
      </div>
      <div class="modal-body">
        <%= render 'shared/providers' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t 'actions.close' %></button>
      </div>
    </div>
  </div>
</div>

app/views/home/sign_in.html.erb
<h2>Sign In</h2>
<hr>

<%= render 'shared/providers' %>

<br>

<p><%= t 'referroll.pp.text' %> <%= link_to t('referroll.pp.title'), '#', class: 'unstyled' %>.</p>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t('models.job.title'), class: 'control-label' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t('models.job.desc'), class: 'control-label' %>
    <%= f.text_area :desc, size: '140x3', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t('models.job.company'), class: 'control-label' %>
    <%= f.text_field :company, class: 'form-control' %>
  </div>
  <% if @job.persisted? %>
  <div class="form-group">
    <%= f.label t('models.job.status'), class: 'control-label' %>&nbsp;
    <%= f.select :status, Job.status.options %>
  </div>
  <% end %>

  <div>
    <%= f.submit t('helpers.submit.save'), class: 'btn btn-primary btn-block' %>
    <%= link_to t('actions.cancel'), jobs_path, class: 'btn btn-default btn-block' %>
  </div>

<% end %>

app/views/jobs/edit.html.erb
<h3><%= t('actions.edit', model: t('models.job.one')) %></h3>
<hr>

<%= render 'form' %>

app/views/jobs/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h3><%= t 'models.job.many' %></h3>
  </div>
  <div class="col-md-2">
    <%= link_to raw("<i class='fa fa-plus'></i> #{t('actions.new', model: t('models.job.one'))}"), new_job_path, { class: "btn btn-sm btn-primary btn-block" } %>
  </div>
</div>

<div class="row">

  <!-- <div class="col-md-2 well well-sm">

    <div class="col-md-4">
      <div class="input-group">
        <input type="text" class="form-control input-sm input-block-level">
        <span class="input-group-btn">
          <button class="btn btn-sm btn-primary" type="button">Search</button>
        </span>
      </div>
    </div> 
    <div style="margin-bottom: 10px;">
      <h4 style="margin-top: 0;"><%= t 'actions.filter' %></h4>
      <hr style="border-top: solid 1px #ccc; margin: 5px 0 10px 0; padding: 0;">
    </div>
    <div style="margin-bottom: 10px;">
      <label><small><%= t 'models.job.status' %>:&nbsp;</small></label><br>
      <select class="input-sm" style="min-width: 140px;">
        <option>All</option>
        <option selected>Open</option>
        <option>Closed</option>
      </select>
    </div>
    <div style="margin-bottom: 10px;">
      <label><small><%= t 'models.job.owner' %>:&nbsp;</small></label>
      <select class="input-sm" style="min-width: 140px; max-width: 140px !important; overflow: hidden;">
        <option style="max-width: 140px !important; overflow: hidden;" selected>All</option>
        <option style="max-width: 140px !important; overflow: hidden;">You</option>
        <option style="max-width: 140px !important; overflow: hidden;">Your teams</option>
      </select>
    </div>
    <hr style="border-top: solid 1px #ccc; margin: 5px 0 10px 0; padding: 0;">
    <div>
      <%= link_to raw("<i class='fa fa-plus'></i> #{t 'actions.new'} #{t 'models.job.one'}"), new_job_path, { class: "btn btn-sm btn-primary", style: "width: 100%;" } %>
    </div>
  </div>
  
  <div class="col-md-10"> -->

  <div class="col-md-12">

    <div class="list-group">

      <% @jobs.each do |job| %>
        <%= link_to(job, { class: "list-group-item" }) do %>
          <!-- {{#if referrals}}
            <span class="badge">{{referrals.length}} referrals</span>
          {{else}} -->
            <button class="btn btn-sm btn-primary pull-right"><i class="fa fa-hand-o-right"></i> ask for referrals</button>
          <!-- {{/if}} -->
          <h4 class="list-group-item-heading">
            <% if job.owned_by?(current_user) %>
              <span class="label label-default label-owner">owner</span> 
            <% else %>
              <span class="label label-default label-owner">helper</span> 
            <% end %>
            <%= job.title %>
          </h4>
          <small class="list-group-item-text">
            <!-- {{#unless open}}<span class="label label-default">closed</span> {{/unless}} -->
            <% if job.closed? %><span class="label label-default"><%= job.status.text.downcase %></span><% end %>
            Posted <%= time_ago_in_words(job.created_at) %> ago.
          </small>
        <% end %>
      <% end %>

    </div>  <!-- list-group -->

  </div> <!-- col-md-10 -->

</div> <!-- row -->

app/views/jobs/new.html.erb
<h3><%= t('actions.new', model: t('models.job.one')) %></h3>
<hr>

<%= render 'form' %>

app/views/jobs/show.html.erb
<h3>
  <%= @job.title %>
  <span class="label label-info pull-right"><%= @job.status.text.downcase %></span>
</h3>
<p><%= @job.desc %></p>
<p><small>Posted <%= time_ago_in_words(@job.created_at) %> ago by <%= @job.owner.name %>.</small></p>
<br>
<p>No referrals yet.</p>

<hr>

<%= link_to t('actions.back'), jobs_path, class: 'btn btn-primary btn-block' %>
<%= link_to 'Edit Job', edit_job_path(@job), class: 'btn btn-default btn-block' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= t 'referroll.name' %> - <%= t 'referroll.slogan' %></title>
  <meta name="description" content="<%= t 'referroll.slogan' %>">
  <meta name="author" content="Brand New Code">
	<%= csrf_meta_tags %>

  <!-- Favicon -->
  <!-- <link rel="icon" href="favicon.ico" type="image/x-icon">
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"> -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <!-- Flatly - Flat and modern Bootstrap theme from Bootswatch -->
  <link href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/flatly/bootstrap.min.css" rel="stylesheet">

  <!-- Font Awesome -->
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Dancing+Script:700' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag "application", :media => "all" %>
  
</head>
<body>

  <%= render 'shared/header' if current_user %>

  <div class="container">

    <%= flash_alert flash[:notice], "info" if flash[:notice] %>

    <%= flash_alert flash[:alert], "warning" if flash[:alert] %>

    <%= flash_alert flash[:success], "success" if flash[:success] %>

    <%= flash_alert flash[:error], "danger" if flash[:error] %>

    <%= yield %>

  </div>

  <footer></footer>

	<!-- Javascript placed at the end of the document so the pages load faster -->

  <!-- Bootstrap core JavaScript -->
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= t 'referroll.name' %> - <%= t 'referroll.slogan' %></title>
  <meta name="description" content="<%= t 'referroll.slogan' %>">
  <meta name="author" content="">
	<%= csrf_meta_tags %>

  <!-- Favicon -->
  <!-- <link rel="icon" href="favicon.ico" type="image/x-icon">
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"> -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <!-- Twitter's Bootstrap 3.1.1 -->
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

  <!-- Font Awesome -->
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Dancing+Script:700' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag "public", :media => "all" %>
  
</head>
<body>

	<%= yield %>

	<!-- Javascript placed at the end of the document so the pages load faster -->

  <!-- Bootstrap core JavaScript -->
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <strong><%= link_to t('referroll.name'), user_path(current_user), class: 'navbar-brand' %></strong>
      <!-- <button type="button" class="navbar-toggle" data-toggle="collapse">
        <span class="icon-user"></span>
      </button> -->
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to t('models.job.many'), "/jobs" %></li>
        <li><%= link_to t('models.referral.many'), "/referrals" %></li>
        <li><a href="#/teams"><%= t('models.team.many') %></a></li>
        <li><a href="#/scores"><%= t('models.score.many') %></a></li>
        <li><a href="#"><%= t('actions.help') %></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- <form class="navbar-form navbar-left">
          <input type="search" class="form-control input-sm" placeholder="Search help">
        </form> -->
        <!-- Normal view -->
        <li class="dropdown hidden-xs">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" style="">
          <i class="fa fa-inbox notification-icon"></i>
          <span class="label label-warning notification-number">5</span>
          <b class="caret notification-caret"></b></a>
          <div class="list-group dropdown-menu dropdown-notification">
            <small><a href="#" class="list-group-item"><span class="label label-info">i</span>&nbsp; New referral for Analista de Testes Sr <small class="pull-right">Just now</small></a></small>
            <small><a href="#" class="list-group-item"><span class="label label-info">i</span>&nbsp; New referral for Estagiário de Marketing Digital  <small class="pull-right">Two minutes ago</small></a></small>
            <small><a href="#" class="list-group-item"><span class="label label-warning">?</span>&nbsp; Jonathan Smith invited you to collaborate on a job <small class="pull-right">Yesterday</small></a></small>
            <small><a href="#" class="list-group-item"><span class="label label-success">!</span>&nbsp; Jonathan Smith accepted your team invite <small class="pull-right">Yesterday</small></a></small>
            <small><a href="#" class="list-group-item"><span class="label label-success">!</span>&nbsp; You acquired the Trophee Badge! <small class="pull-right">One year ago</small></a></small>
          </div>
          <!-- <div class="list-group dropdown-menu dropdown-notification">
            <a href="#" class="list-group-item">
              <p class="list-group-item-heading">New referral for Analista de Testes Sr <span class="label label-info pull-right">i</span></p>
              <small class="list-group-item-text">Just now</small>
            </a>
            <a href="#" class="list-group-item">
              <p class="list-group-item-heading">New referral for Estagiário de Marketing Digital <span class="label label-info pull-right">i</span></p>
              <small class="list-group-item-text ">Two hours ago</small>
            </a>
            <a href="#" class="list-group-item">
              <p class="list-group-item-heading">Jonathan Smith invited you to collaborate on a job <span class="label label-warning pull-right">?</span></p>
              <small class="list-group-item-text ">Yesterday</small>
            </a>
            <a href="#" class="list-group-item">
              <p class="list-group-item-heading">Jonathan Smith accepted your team invite <span class="label label-success pull-right">!</span></p>
              <small class="list-group-item-text ">Yesterday</small>
            </a>
            <a href="#" class="list-group-item">
              <p class="list-group-item-heading">You acquired the Trophee Badge! <span class="label label-success pull-right">!</span></p>
              <small class="list-group-item-text ">One year ago</small>
            </a>
          </div> -->
        </li>
        <li class="dropdown hidden-xs">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <img src="https://secure.gravatar.com/avatar/d0d38d7d12378a13afcdf6caab654434?s=40" class="img-rounded"> <b class="caret"></b></a>
          <ul class="dropdown-menu dropdown-profile">
            <li><%= link_to raw("<i class='fa fa-user'></i>&nbsp; #{t('actions.profile')}"), user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to raw("<i class='fa fa-sign-out'></i>&nbsp; #{t('actions.sign-out')}"), sign_out_url %></li>
          </ul>
        </li>
        <!-- Extra small view (mobile) -->
        <li class="hidden-sm hidden-md hidden-lg"><a href="#"><%= t('models.notification.many') %> &nbsp;<span class="label label-warning">3</span></a></li>
        <li class="hidden-sm hidden-md hidden-lg"><a href="#"><%= t('actions.profile') %></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_providers.html.erb
<p><%= link_to raw("<i class='fa fa-fw fa-2x fa-linkedin-square'></i> #{t 'actions.sign-in-with'} Linkedin"), "/auth/linkedin", class: "btn btn-lg btn-block btn-linkedin" %></p>
<p><%= link_to raw("<i class='fa fa-fw fa-2x fa-google-plus-square'></i> #{t 'actions.sign-in-with'} Google&nbsp;&nbsp;"), "/auth/google", class: "btn btn-lg btn-block btn-google" %></p>

app/views/users/show.html.erb
<% if current_user %>

	<p>Signed in as <%= current_user.name %>. <%= link_to "Sign out", sign_out_path %></p>

<% end %>